fix: config loaded debug statement logs secrets
opentdf/platform pull request #1010
Opened 2024-06-20 14:11 UTC by mustyantsev

address https://github.com/opentdf/platform/issues/751

2024-06-20 15:59 UTC, dmihalcik-virtru requested changes

2024-06-20 15:59 UTC, dmihalcik-virtru commented on service/pkg/server/start.go
> +	sensitiveWords := []string{"password", "clientsecret"}
Can these be taken out of the config instead of hard coded?

2024-06-20 15:59 UTC, dmihalcik-virtru commented on service/pkg/util/redact.go
> +				redacted.Field(i).SetString("REDACTED")
```suggestion
				redacted.Field(i).SetString("***")
```

This mirrors github action redactions: 

<img width="702" alt="image" src="https://github.com/opentdf/platform/assets/38867245/7d589b26-52cf-4308-8b7d-5c5267b18e2f">

2024-06-20 16:02 UTC, strantalis commented
Did we look into masq pkg or having the Config implement `LogValue`?

https://github.com/m-mizutani/masq

https://betterstack.com/community/guides/logging/logging-in-go/#hiding-sensitive-fields-with-the-logvaluer-interface

2024-06-24 13:54 UTC, dmihalcik-virtru approved these changes

2024-06-24 13:59 UTC, merged