fix(db): invalid uuid error message
opentdf/platform pull request #633
Opened 2024-04-22 15:25 UTC by suchak1

2024-04-22 16:43 UTC, jakedoublev commented
@sievdokymov-virtru this meets your needs, correct?

2024-04-22 16:48 UTC, jakedoublev requested changes
This is nice cleanup, but it looks like the same error is returned from this wrapper function, `db.ErrUUIDInvalid`, which reads `value not a valid UUID`? In that case, it seems like it will still not be clear to the requester that the _member_ id was invalid and not the _value_ id as the original opener of the issue found.

2024-04-22 18:23 UTC, suchak1 commented
Server responses are again with the `StatusifyError` fx which replaces `ErrUUIDInvalid` with `ErrTextEnumValueInvalid`. I believe external users and @sievdokymov-virtru use the server / AttributeService to place the request in https://github.com/opentdf/platform/issues/505. If we believe internal developers will be confused by `ErrUUIDInvalid`, I can replace the text for that as well.

2024-04-22 18:44 UTC, jakedoublev approved these changes

2024-04-23 12:23 UTC, strantalis approved these changes

2024-04-23 12:28 UTC, merged