Update KAS access provider and crypto system
opentdf/platform pull request #807
Opened 2024-05-14 16:57 UTC by pflynn-virtru

Refactored the Key Access Service provider to use a pointer receiver and updated the cryptography system for better private-public key management. Enhanced the elliptic curve digital signature algorithm (ECDSA) methods, and included functions to generate a symmetric key, ephemeral keys, and a session key. Also fixed minor issues and commented out code blocks.

2024-05-17 14:19 UTC, sujankota requested changes

2024-05-17 14:19 UTC, sujankota commented on service/internal/security/standard_crypto.go
> +	pubKey, ok := pubKeyInterface.(*ecdsa.PublicKey)
This should ECDH not ECDSA

2024-05-17 14:22 UTC, sujankota commented on service/internal/security/standard_crypto.go
> +	pubKey, ok := pubKeyInterface.(*ecdsa.PublicKey)
Session key = KDF(ECDH(sdk-session-public-key, kas-ephemeral-private-key), 'L1L')

L1L is the salt

2024-05-17 14:23 UTC, sujankota commented on service/internal/security/standard_crypto.go
> +	pubKey, ok := pubKeyInterface.(*ecdsa.PublicKey)
ocrypto module should have this functionality.

2024-05-17 14:24 UTC, sujankota commented on service/internal/security/standard_crypto.go
> +	ecPrivateKey     *ecdsa.PrivateKey
This should be ECDH

2024-06-20 19:43 UTC, cassandrabailey293 commented
this was merged with https://github.com/opentdf/platform/issues/777 . closing this pr.

2024-06-20 19:43 UTC, closed without merging